### ISSUE TITLE
pypi & artifact naming

### ISSUE THREAD

**Issue by dch** [simonw/llm-claude-3#12]
the naming scheme for published artifacts seems to have switched to using `_` instead of `-`

      llm-claude-3-0.3.tar.gz -> llm_claude_3-0.4.1.tar.gz

Is this intended, or will it be reverted in a future release?

I'm the maintainer for your FreeBSD llm-* related ports, and I'm ok to rename the
port to match this new scheme, if that's intentional, but if it will flip back
in a future release I'll just use a small workaround until the next bump.

**Comment by simonw** [comment]
Not sure what happened here, sorry. Might have been because I switched to using this mechanism for publishing:

https://github.com/simonw/llm-claude-3/blob/b5b19b7644afd671c5d177a5cd980b7f85065a5c/.github/workflows/publish.yml#L44-L51

I do not plan to make any future changes to that.
