### ISSUE TITLE
Support for Claude 3 Haiku

### ISSUE THREAD

**Issue by simonw** [simonw/llm-claude-3#3]
Released today: https://twitter.com/AnthropicAI/status/1764653830468428150

https://www.anthropic.com/news/claude-3-haiku

**Comment by simonw** [comment]
It's not listed here yet: https://docs.anthropic.com/claude/docs/models-overview#model-recommendations

![Latest API. Claude 3 Opus = claude-3-opus-20240229, Claude 3 Sonnet =  claude-3-sonnet-20240229, Claude 3 Haiku = Coming soon](https://github.com/simonw/llm-claude-3/assets/9599/261a8a99-ecdd-4006-bcec-654823d0c047)

**Comment by simonw** [comment]
Found it in the Workbench:

![Screenshot of model selection in Workbench](https://github.com/simonw/llm-claude-3/assets/9599/a2a8e81d-b57a-401a-bba2-d31d70f67d51)

    claude-3-haiku-20240307

**Comment by simonw** [comment]
```bash
llm -m claude-3-haiku 'a long poem about an armadillo'
```
```
Here is a long poem about an armadillo:

The Armadillo's Odyssey

Beneath the Texas sun, where mesquite trees sway,
An armadillo sets forth on its curious way.
Its armor-plated shell, a shield so true,
Protects this wanderer as it forges anew.

With each tentative step, it scurries along,
Its keen senses alert, its movements strong.
Sniffing the air for insects, its truest delight,
The armadillo presses on, through day and night.

Through thickets and thorns, it carves out its path,
Undaunted by obstacles, its patience hath.
A creature of habit, it follows its trail,
Seeking sustenance, never once does it wail.

Over rocky terrain, through sandy arroyos,
The armadillo traverses, its gait never slows.
It digs with sharp claws, burrowing deep,
A cozy abode where it can safely sleep.

When danger draws near, it curls in a ball,
Its armor protecting, standing tall.
Predators prowl, but cannot penetrate,
The armadillo's defenses, its ultimate fate.

This resilient creature, so humble and wise,
Carries on with its life, under endless skies.
From dusk until dawn, it forages with might,
The armadillo's odyssey, an endless delight.

Through seasons of change, it adapts and survives,
This ancient survivor, its spirit thrives.
A testament to endurance, a model so true,
The armadillo's journey, a wonder to pursue.
```
With `time` in front of it took `1.00s user 0.09s system 20% cpu 5.458 tota`

Compare with `opus` which took:

```bash
time llm -m claude-3-opus 'a long poem about an armadillo
```
...
```
1.05s user 0.09s system 4% cpu 24.977 total
```

**Comment by simonw** [comment]
![I run the prompt 'fun facts about armadillos' - Claude 3 Haiku outputs text at a pretty snappy rate: Here are some fun facts about armadillos: 1. Armadillos are the only mammals that have a protective shell. This shell is made up of bony plates covered with leathery skin. 2. Armadillos can jump 3-4 feet into the air to scare off predators. When threatened, they also have the ability to roll up into a ball, protecting their unarmored stomach. 3. Armadillos are excellent diggers and can burrow into the ground quickly to escape danger. They use their sharp claws to dig dens, search for food, and create a network of tunnels. 4. Armadillos are the only living mammals that can contract leprosy. This is due to their unusually low body temperature, which is ideal for the leprosy bacteria to thrive. 5. Armadillos have excellent night vision and a keen sense of smell, which helps them locate their food sources, such as insects, larvae, and small vertebrates.](https://github.com/simonw/llm-claude-3/assets/9599/d259b6d1-ea92-4af5-81db-7aab74531318)

**Comment by jeffmcjunkin** [comment]
Confirmed working for me already! Thanks for the fast turnaround as always!

**Comment by rdslw** [comment]
what would be proper way to install plugin update if I have it already installed?

**Comment by clarity99** [comment]
I'm curious as to how to update plugins as well...
